appId: com.example.trend_sdet
name: "Smoke: Product Detail Opens"
tags:
  - smoke
---
- runFlow: ../subflows/launch_app_clean.yaml

# Wait for products to load
- extendedWaitUntil:
    visible:
      id: "home_content"
    timeout: 15000

# Open first product
- runFlow: ../subflows/open_first_product.yaml

# Assert PDP elements
- extendedWaitUntil:
    visible:
      id: "detail_product_title"
    timeout: 15000
- assertVisible:
    id: "detail_product_price"
- assertVisible:
    id: "detail_add_to_cart_button"
